### PR TITLE
Add considerations markdown and update readme markdown

### PR DESCRIPTION
**Pull request by Dpalazzari**
- adds considerations markdown file
- adds link to considerations.md to readme file
- Updates README markdown file

one reviewer @kheppenstall @lucyconklin @wlffann 

FYI @case-eee

### CODE REVIEW

**Comment by kheppenstall** [comment]
@Dpalazzari Thanks for doing this. Work looks great and I love the idea of doing the screenshots in the `considerations.md`! Once Travis passes then I'm happy to merge this in.

**Comment by kheppenstall** [comment]
@Dpalazzari Seems like these two PRs are failing on Travis for the same reason. It may be that one of our test dependencies, [react-addons-test-utils](https://www.npmjs.com/package/react-addons-test-utils) is now deprecated.

**Comment by kheppenstall** [comment]
We had been seeing this deprecation warning recently:

screen shot 2017-04-12 at 5 23 14 pm

**Comment by kheppenstall** [comment]
This [issue](https://github.com/airbnb/enzyme/issues/875) has some enzyme contributors discussing what may be a related issue.

**Comment by Dpalazzari** [comment]
Such an annoyance. I just got out of a pairing, have you made any progress in following this error? @kheppenstall

**Comment by Dpalazzari** [comment]
npm i --save-dev react-test-renderer @kheppenstall

**Comment by lucyconklin** [comment]
@Dpalazzari Thanks so much! These look great!

**Pull request merged**
