### PR TITLE
Replace current favicon with window

### PR DESCRIPTION
**Pull request by kheppenstall**
Looks like this on the browser tab: 
screen shot 2017-04-12 at 1 05 53 pm

### CODE REVIEW

**Comment by kheppenstall** [comment]
@Dpalazzari @lucyconklin @wlffann I can't figure out why travis is failing here. The only file changed is the `favicon.ico`.

**Comment by Dpalazzari** [comment]
Perhaps this holds the answer @kheppenstall https://github.com/travis-ci/travis-ci/issues/7119

**Comment by kheppenstall** [comment]
Removed the WIP status since its not really in progress. Once I figure out how to make this agree with Travis it can be merged in.

**Comment by kheppenstall** [comment]
Thanks for fixing the travis @Dpalazzari !!!

**Pull request merged**
